<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="Faults6" Id="{19469f92-2967-441c-8541-f1bae9feeb43}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Faults6
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Faults6">
      <LineId Id="10" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>