<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="Forces6" Id="{c412c0a2-882b-4d65-a447-e77bb63c950b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Forces6
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Forces6">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>