<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="Main6" Id="{cf42c77a-3f4f-4d11-8e65-60309e7f1d7b}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Main6
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Main6">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>