<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="Reset6" Id="{948c74cf-5c3d-414a-8f30-2fa391cefd79}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Reset6
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Reset6">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>