<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="Sequence6" Id="{060c4ca8-4616-44e1-89c3-77f69f32f5a7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Sequence6
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Sequence6">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>