<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="Faults1" Id="{b31f38bf-7663-4012-8b28-87ccca645ac4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Faults1
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Faults1">
      <LineId Id="10" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>