<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="Forces1" Id="{ddc47e63-eca3-4693-bd97-1701cc096492}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Forces1
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Forces1">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>