<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="Main1" Id="{d4cb2f5e-1b25-4772-ac9c-f411bc2a3341}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Main1
VAR
	Sequence:Sequence1;
	Forces:Forces1;
	Reset:Reset1;
	Faults:Faults1;	

	bExecute: BOOL;
	FB_CoEAX8000SetPositionOffset1:FB_CoEAX8000SetPositionOffset;
	FB_CoEAX8000SetPositionOffset2:FB_CoEAX8000SetPositionOffset;
	FB_CoEAX8000SetPositionOffset3:FB_CoEAX8000SetPositionOffset;
	bExecute2: BOOL;
	bExecute3: BOOL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[//Cyclic Call to the Station FBs 
Sequence();
Forces();
Reset();
Faults();
]]></ST>
    </Implementation>
    <LineIds Name="Main1">
      <LineId Id="103" Count="4" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>