<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="Reset1" Id="{2268c0fe-288a-4490-aa7d-0ba072bf20b2}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Reset1
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Reset1">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>