<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="Faults4" Id="{5e3e73bf-0b44-43c7-93a4-c3cd3f239304}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Faults4
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Faults4">
      <LineId Id="10" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>