<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="Forces4" Id="{d56f4d88-04e3-4b2c-89b6-4800afcabbe7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Forces4
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Forces4">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>