<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="Main4" Id="{1f59f9a7-d9e9-4ba7-9582-5be5c950cb6a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Main4
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Main4">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>