<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="Sequence4" Id="{2f457965-dc86-4899-85e2-e131921b13d1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Sequence4
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Sequence4">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>