<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="Faults3" Id="{da3620e9-a87e-482d-bcc6-d5ae8b33990f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Faults3
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Faults3">
      <LineId Id="10" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>