<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="Faults2" Id="{48406e60-56d9-479c-aae9-1deb43b91d18}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Faults2
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Faults2">
      <LineId Id="10" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>