<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="Forces2" Id="{ab65772c-f89c-4b17-a551-a19d9cbf8774}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Forces2
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Forces2">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>