<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="Reset2" Id="{c18ff4d2-bf50-48ff-89d8-b8e3792d79c2}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Reset2
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Reset2">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>