<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="Sequence2" Id="{0291e4fa-66ca-46da-b49b-c47f77c0d442}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Sequence2
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Sequence2">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>