<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="Faults5" Id="{15c86bd7-c3d2-4640-85c3-db20ee55a3cc}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Faults5
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Faults5">
      <LineId Id="10" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>