<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="Forces5" Id="{4acd2301-6cae-4c87-b50e-09f23b809773}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Forces5
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Forces5">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>