<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="Main5" Id="{686a13c3-5a9c-4afd-94a3-f410a29c8d2f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Main5
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Main5">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>