<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="Reset5" Id="{d6eb2a38-1872-4524-ad8d-4a058018357e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Reset5
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Reset5">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>