<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="Sequence5" Id="{fa7ef538-1527-401e-8789-806f3b39bcb1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Sequence5
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Sequence5">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>